# Site settings
title: Jekyll shop powered by Snipcart
email: geeks@snipcart.com
description: Here's a quick demo showing the integration between Snipcart and Jekyll. We hope you like it!
baseurl: "/snipcart-jekyll-integration" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Snipcart
github_username:  Snipcart
api_key: Y2ZhODhkMjItNTgyYy00ZTE2LThjMjAtY2QwNmRjMGU4M2MyNjM2MzIyOTU3ODU3NTEyNjY4

# Build settings
markdown: kramdown
collections:
  products:
    output: true
